swagger:
  - blockchain-indexer
  - inscription-indexer
  - brc20-indexer
  - runes-indexer
  - alkanes-indexer
  - inscribe
  - brc20-marketplace
  - runes-marketplace
  - alkanes-marketplace
  - collection-marketplace
  - domain-marketplace
  - brc20-swap
  - fractal
  - cat20-dex
  - collection-indexer
doc:
  - blockchain-indexer
  - inscription-indexer
  - brc20-indexer
  - runes-indexer
  - alkanes-indexer
  - inscribe
  - brc20-marketplace
  - runes-marketplace
  - alkanes-marketplace
  - collection-marketplace
  - domain-marketplace
  - brc20-swap
  - fractal
  - cat20-dex
  - collection-indexer
