swagger:
  - basic-indexer
  - inscription-indexer
  - brc20-indexer
  - runes-indexer
  - inscribe
  - marketplace
  - brc20-swap
  - fractal
  - cat20-dex
  - collection-indexer
doc:
  - alkanes-api
